version: '3.8'

services:
  mongoDatabase:
    container_name: mongoDatabase
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - type: bind
        source: ./database
        target: /database/db
    networks:
      - account_summary_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: account_summary_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${PORT:-8080}:8080'
    volumes:
      - ./assets:/app/assets:ro
      - ./src/templates:/app/src/templates:ro
    depends_on:
      - mongoDatabase
    networks:
      - account_summary_network

volumes:
  mongoDatabase_data:
    driver: local

networks:
  account_summary_network:
    driver: bridge
