version: '3.8'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017/transaction_summary
    depends_on:
      - mongo
    volumes:
      - ./assets:/app/assets:ro
      - ./frontend.html:/app/frontend.html:ro
    restart: unless-stopped
    networks:
      - app-network

  mongo:
    image: mongo:7.0
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=transaction_summary
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
